log more to /tmp/switch_php.debug.log

diff --git a/files/switch_php b/files/switch_php
--- a/files/switch_php
+++ b/files/switch_php
@@ -13,6 +13,9 @@ export DBGLOG=/tmp/switch_php.debug.log
 export COMPOSER_PROCESS_TIMEOUT="${COMPOSER_PROCESS_TIMEOUT:-900}" # default is COMPOSER_PROCESS_TIMEOUT=300
 export COMPOSER_MEMORY_LIMIT="${COMPOSER_MEMORY_LIMIT:-2G}"
 
+function logit() {
+    echo -e "$*" | tee -a "$DBGLOG"
+}
 
 type -p composer &>/dev/null || {
     # composer_version=$(composer --version | cut -d ' ' -f3 | cut -d. -f-2 | tr -d '.')
@@ -70,7 +73,7 @@ function is_php_installed() {
     if ! test -e $PHP_BIN_PATH; then
         return 1
     fi
-    echo $(${PHP_BIN_PATH}/php -r 'echo "\n".PHP_VERSION;' | tail -1 | cut -d. -f-2)
+    echo $(${PHP_BIN_PATH}/php -r 'logit "\n".PHP_VERSION;' | tail -1 | cut -d. -f-2)
 }
 
 function export_php_env_and_path() {
@@ -87,7 +90,7 @@ function export_php_env_and_path() {
         # add path early
         export PATH="$COMPOSER_BIN_PATH:$PATH"
 
-        echo "⚡️ PATH updated for composer global ${COMPOSER_BIN_PATH}"
+        logit "⚡️ PATH updated for composer global ${COMPOSER_BIN_PATH}"
     fi
 
     local PHP_BIN_PATH
@@ -102,7 +105,7 @@ function export_php_env_and_path() {
         export PATH=$(echo $PATH | sed -E 's,/usr/local/opt/php@[[:digit:]\.]+/bin:,,g')
         # add path early
         export PATH="$PHP_BIN_PATH:$PATH"
-        echo "⚡️ PATH updated for PHP ${PHP_BIN_PATH}"
+        logit "⚡️ PATH updated for PHP ${PHP_BIN_PATH}"
     fi
 
 }
@@ -120,17 +123,17 @@ function php_cli_switch() {
         # composer_global_install $php_ver
 
     else
-        echo "Cannot find PHP_BIN_PATH=$PHP_BIN_PATH"
+        logit "Cannot find PHP_BIN_PATH=$PHP_BIN_PATH"
     fi
 
 }
 
 function php_cli_from_valet() {
     [ -e .valetphprc ] || {
-        [ -e artisan ] && echo -e "Cannot find .valetphprc, try \necho php@8.1 > ./.valetphprc"
+        [ -e artisan ] && logit "Cannot find .valetphprc, try \necho php@8.1 > ./.valetphprc"
         return 2
     }
-    echo "Found '$(pwd)/.valetphprc' - upgrade to valet 3.x and use 'valet isolate php@n.n'"
+    logit "Found '$(pwd)/.valetphprc' - upgrade to valet 3.x and use 'valet isolate php@n.n'"
     local php_ver=$(grep 'php@' .valetphprc)
     [ ! -z "$php_ver" ] && php_cli_switch $php_ver || false
 }
@@ -140,13 +143,13 @@ function php_show_modules() {
     # show loaded modules
 
     local modules="$(echo $PHP_EXTENSIONS | sed 's#shivammathur/extensions/##g' | tr ' ' '|')"
-    echo "php-fpm modules : $(php-fpm -m | grep -iE "$modules" | tr A-Z a-z | sort | uniq | xargs)"
-    echo "php modules     : $(php -m | grep -iE "$modules" | tr A-Z a-z | sort | uniq | xargs)"
+    logit "php-fpm modules : $(php-fpm -m | grep -iE "$modules" | tr A-Z a-z | sort | uniq | xargs)"
+    logit "php modules     : $(php -m | grep -iE "$modules" | tr A-Z a-z | sort | uniq | xargs)"
 }
 
 function composer_global_clean() {
 
-    echo "${FUNCNAME[0]} $*" >>$DBGLOG 2>&1
+    logit "${FUNCNAME[0]} $*" >>$DBGLOG 2>&1
 
     if [ $# -eq 1 ]; then
         export COMPOSER_HOME="$(get_composer_home $1)"
@@ -159,7 +162,7 @@ function composer_global_clean() {
         /bin/rm -f "${COMPOSER_HOME}"/composer.{json,lock} 2>/dev/null || true
         /bin/rm -rf "${COMPOSER_HOME}"
     else
-        # echo "Cannot clean COMPOSER_HOME=$COMPOSER_HOME" >&2
+        # logit "Cannot clean COMPOSER_HOME=$COMPOSER_HOME" >&2
         return 1
     fi
 
@@ -168,10 +171,10 @@ function composer_global_clean() {
 
 function composer_global_install() {
 
-    echo "${FUNCNAME[0]} $*" >>$DBGLOG 2>&1
+    logit "${FUNCNAME[0]} $*" >>$DBGLOG 2>&1
 
     [[ $# -ne 1 ]] && {
-        echo "Usage: ${FUNCNAME} php_version - required use n.n style"
+        logit "Usage: ${FUNCNAME} php_version - required use n.n style"
         return 1
     }
     local php_ver=$(resolve_php_ver $1) # n.n format
@@ -182,10 +185,10 @@ function composer_global_install() {
     # other packages to consider
     local consider_package="slince/composer-registry-manager "
 
-    echo "⚡️ composer global require for $php_ver"
+    logit "⚡️ composer global require for $php_ver"
     case "$php_ver" in
     5.6)
-        echo "not supported" && return 1
+        logit "not supported" && return 1
         ;;
     8.0)
         composer global config --no-interaction minimum-stability alpha
@@ -228,14 +231,14 @@ function composer_global_install() {
 
 function valet_uninstall() {
 
-    echo "${FUNCNAME[0]}"
+    logit "${FUNCNAME[0]}"
 
     #
     # Help brew after valet's touched things.
     #
     # sudo chown -R $(id -un) /usr/local/Cellar/{php*,dnsmasq*,nginx*} >>$DBGLOG 2>&1 || true
 
-    echo "🤞 Uninstall valet"
+    logit "🤞 Uninstall valet"
     type -p valet >>$DBGLOG 2>&1 && yes | valet uninstall --force --no-interaction >>$DBGLOG 2>&1 || true
 
     if composer global --no-interaction remove laravel/valet >>$DBGLOG 2>&1; then
@@ -244,20 +247,20 @@ function valet_uninstall() {
         echo ' Valet not installed via composer global $COMPOSER_HOME'
     fi
 
-    echo "🤞 Uninstall brew services"
+    logit "🤞 Uninstall brew services"
     for formula in dnsmasq nginx; do
         sudo brew services stop $formula >>$DBGLOG 2>&1 || true
         sudo brew uninstall --force --ignore-dependencies "$formula" >>$DBGLOG 2>&1 || sudo rm -rf /usr/local/Cellar/$formula || true
         brew uninstall --force --ignore-dependencies "$formula" >>$DBGLOG 2>&1 || sudo rm -rf /usr/local/Cellar/$formula || true
     done
 
-    echo "🤞 Force tidyup of empty brew formula directories"
+    logit "🤞 Force tidyup of empty brew formula directories"
     find /usr/local/Cellar -type d -empty -maxdepth 1 -exec rm -rf {} \; || true
 
     [ -d ~/.valet ] && sudo rm -r ~/.valet >>$DBGLOG 2>&1 || true
     [ -d ~/.config/valet ] && sudo rm -r ~/.config/valet >>$DBGLOG 2>&1 || true
 
-    echo "🤞 Force tidyup of php / pecl / pear directories"
+    logit "🤞 Force tidyup of php / pecl / pear directories"
     sudo rm -rf /usr/local/etc/php/* /private/tmp/pear/* /usr/local/lib/php/* /usr/local/share/php* /usr/local/share/pear* >>$DBGLOG 2>&1 || true
     sudo rm -rf /usr/local/etc/php/* /private/tmp/pear/* /usr/local/lib/php/* /usr/local/share/php* /usr/local/share/pear* >>$DBGLOG 2>&1 || true
     sudo rm -rf /private/tmp/pear/ >>$DBGLOG 2>&1 || true
@@ -268,9 +271,9 @@ function valet_uninstall() {
 
 
 function valet_install() {
-    echo "${FUNCNAME[0]} $*"
+    logit "${FUNCNAME[0]} $*"
 
-    echo "⚡️ Prepare existing php/valet"
+    logit "⚡️ Prepare existing php/valet"
     php_ver=$1
 
     export_php_env_and_path $php_ver
@@ -280,39 +283,39 @@ function valet_install() {
 
     if test -z $valet || ! test -e $valet; then
 
-        echo "🤔 Missing php/valet - restoring via composer"
+        logit "🤔 Missing php/valet - restoring via composer"
         composer_global_install ${php_ver}
 
         if ! test -e $valet; then
-            echo "🤔 Looks like we've broken it - still can't find valet at ${valet}!"
-            echo -e "🧐 Try\nphp_uninstall, then php_install $php_ver\n"
+            logit "🤔 Looks like we've broken it - still can't find valet at ${valet}!"
+            logit "🧐 Try\nphp_uninstall, then php_install $php_ver\n"
             return 1
         fi
-        echo "⚡️ Valet restored at $valet"
+        logit "⚡️ Valet restored at $valet"
     fi
 
     export_php_env_and_path $php_ver
     valet="$(which valet)"
 
     if ! $valet trust &>/dev/null; then
-        echo "⚡️ Valet ($valet) exists but we need to run '$valet install'." | tee -a $DBGLOG
+        logit "⚡️ Valet ($valet) exists but we need to run '$valet install'." | tee -a $DBGLOG
         $valet install
     fi
 
     # permissions for interrupt free php switching with valet
-    echo "⚡️ Trust in Valet !"
+    logit "⚡️ Trust in Valet !"
     sudo -v && $valet trust
 
     # sometimes brew services php-fpm fails - this is a permissions issue that creeps in somewhere.
     (pushd /usr/local/etc/ && sudo chown -R $(whoami) php* && popd) >>$DBGLOG 2>&1 || {
         echo -n "🤔 Looks like permissions reset failed"
-        echo -e " try\n  brew postinstall $PHP_VER_TARGET --verbose --debug"
+        logit " try\n  brew postinstall $PHP_VER_TARGET --verbose --debug"
     }
 }
 
 function php_install_via_valet() {
 
-    echo "${FUNCNAME[0]} $*"
+    logit "${FUNCNAME[0]} $*"
     sudo -v
 
     if test -r $HOME/.dotfile_lastrun; then
@@ -330,12 +333,12 @@ function php_install_via_valet() {
     #
 
     [[ $# -ne 1 ]] && {
-        echo "function ${FUNCNAME} php_version - required use n.n style"
+        logit "function ${FUNCNAME} php_version - required use n.n style"
         return 1
     }
 
     if ! type -p composer >>$DBGLOG 2>&1; then
-        echo "🤔 Cannot find composer - cannot progress!"
+        logit "🤔 Cannot find composer - cannot progress!"
         return 1 # composer is not installed
     fi
     local php_version_available=$(brew list -1 --formula | grep php@ | head -1)
@@ -345,12 +348,23 @@ function php_install_via_valet() {
     PHP_VER_TARGET="$(resolve_php_ver $1)"
     PHP_VER_CURRENT="$(resolve_php_ver $(get_php_version))"
 
+    # fix permissions
+    logit "⚡️ fix php permissions"
+    #sudo chown -R $(id -un) /usr/local/Cellar/{php*,dnsmasq*,nginx*} >>$DBGLOG 2>&1 || true
+    sudo chown -R $(id -un) /usr/local/Cellar/php* >>$DBGLOG 2>&1 || true
+    sudo chmod -R 755 /usr/local/Cellar/php* >>$DBGLOG 2>&1 || true
+
     # =========================================================================
     #
     #   CURRENT PHP VERSION: Ensure existing installation is ready
     #
     valet_install $PHP_VER_CURRENT || return 1
-    echo "⚡️ Switching from ${PHP_VER_CURRENT}"
+    logit "⚡️ Switching from ${PHP_VER_CURRENT}"
+
+    logit "⚡️ fix php permissions"
+    #sudo chown -R $(id -un) /usr/local/Cellar/{php*,dnsmasq*,nginx*} >>$DBGLOG 2>&1 || true
+    sudo chown -R $(id -un) /usr/local/Cellar/php* >>$DBGLOG 2>&1 || true
+    sudo chmod -R 755 /usr/local/Cellar/php* >>$DBGLOG 2>&1 || true
 
     # =========================================================================
     #
@@ -358,11 +372,13 @@ function php_install_via_valet() {
     #
     # we need to do this for php versions < 7.4
 
-    echo "⚡️ Installing shivammathur/php/$PHP_VER_TARGET to ensure 'valet use' works for all version of php"
-    HOMEBREW_NO_INSTALL_CLEANUP=false brew reinstall --force -q shivammathur/php/$PHP_VER_TARGET >>$DBGLOG 2>&1
+    logit "⚡️ Installing shivammathur/php/$PHP_VER_TARGET to ensure 'valet use' works for all version of php"
+    HOMEBREW_NO_INSTALL_CLEANUP=false brew reinstall --force -q shivammathur/php/$PHP_VER_TARGET redis >>$DBGLOG 2>&1
+
+    read -p "About to switch via 'valet use' $PHP_VER_TARGET - press enter to continue."
     valet use $PHP_VER_TARGET # install php
 
-    echo -e "⚡️ Add php extensions\n$(echo $PHP_EXTENSIONS | xargs -n 1)\n"
+    logit "⚡️ Add php extensions\n$(echo $PHP_EXTENSIONS | xargs -n 1)\n"
     php_ver=$(echo $PHP_VER_TARGET | cut -d@ -f2)
     for ext in $PHP_EXTENSIONS; do
         forumla="${ext}@${php_ver}"
@@ -372,16 +388,16 @@ function php_install_via_valet() {
     valet_install $PHP_VER_TARGET || return 2 # install valet via composer for this php
 
     # This might be required as brew services sometimes fail
-    echo "⚡️ brew postinstall $PHP_VER_TARGET (forced to run)"
+    logit "⚡️ brew postinstall $PHP_VER_TARGET (forced to run)"
     brew postinstall $PHP_VER_TARGET | grep -E 'Postinstalling|update-channels'
 
-    echo "⚡️ Switched to $PHP_VER_TARGET"
-    echo "⚡️ Valet restarting $PHP_VER_TARGET"
+    logit "⚡️ Switched to $PHP_VER_TARGET"
+    logit "⚡️ Valet restarting $PHP_VER_TARGET"
     # valet install
     valet restart
 
     sudo brew services list
-    echo "🪲 debug logs at $DBGLOG"
+    logit "🪲 debug logs at $DBGLOG"
 
 }
 
@@ -389,7 +405,7 @@ function php_install() {
     #
     # php_install - run this once on new machine
     #
-    echo "✨ ${FUNCNAME[0]} $*"
+    logit "✨ ${FUNCNAME[0]} $*"
 
     sudo -v
     #
@@ -398,22 +414,22 @@ function php_install() {
     # Assumption is via brew bundle .Brewfile and we have tapped 'shivammathur/php' and 'shivammathur/extensions'
     #
     if ! type -p php >>$DBGLOG 2>&1; then
-        echo "✨ Install Brew's shivammathur/php/php"
-        HOMEBREW_NO_INSTALL_CLEANUP=true brew reinstall --force -q shivammathur/php/php | tee -a $DBGLOG &>/dev/null
+        logit "✨ Install Brew's shivammathur/php/php"
+        HOMEBREW_NO_INSTALL_CLEANUP=true brew reinstall --force -q shivammathur/php/php redis | tee -a $DBGLOG &>/dev/null
         #brew reinstall --force -q shivammathur/php/php
     else
-        echo "✨ PHP currently installed ($(php -v | head -1))"
+        logit "✨ PHP currently installed ($(php -v | head -1))"
     fi
 
     #
     # Ensure composer at 2.2 is installed
     #
     if ! type -p composer >>$DBGLOG 2>&1; then
-        echo "✨ Install missing composer"
+        logit "✨ Install missing composer"
         brew install composer | tee -a $DBGLOG && \
         composer self-update --2.2 | tee -a $DBGLOG # required for version of php < 7.2.5
     else
-        echo "✨ Composer is installed ($(composer --version), $(which composer))" || true
+        logit "✨ Composer is installed ($(composer --version), $(which composer))" || true
     fi
 
     brew cleanup -q >>$DBGLOG 2>&1 || true
@@ -424,7 +440,7 @@ function php_install() {
     local PHP_VER_TARGET="$(resolve_php_ver $target_php_version)"
     local PHP_VER_CURRENT="$(resolve_php_ver $current_php_version)"
 
-    echo "✨ Install PHP & Composer Global packages specific to PHP Version ($PHP_VER_TARGET)"
+    logit "✨ Install PHP & Composer Global packages specific to PHP Version ($PHP_VER_TARGET)"
 
     if [ -n "$current_php_version" ]; then
         #
@@ -438,14 +454,14 @@ function php_install() {
         export_php_env_and_path $current_php_version
         if ! composer global --no-interaction show -i -D -n laravel/valet &>/dev/null; then
 
-            echo "⚡️ Valet not installed for current php version via composer at $COMPOSER_HOME"
+            logit "⚡️ Valet not installed for current php version via composer at $COMPOSER_HOME"
 
             composer_global_install $current_php_version || {
-                echo "🧐 something is not correct with the composer global setup, try php_uninstall !"
+                logit "🧐 something is not correct with the composer global setup, try php_uninstall !"
                 return 3
             }
             export_php_env_and_path $current_php_version
-            echo "install valet now"
+            logit "install valet now"
             valet_install $current_php_version
         fi
     fi
@@ -455,14 +471,14 @@ function php_install() {
     #
     if [ -n "$PHP_VER_TARGET" -a -n "$PHP_VER_CURRENT" -a "$PHP_VER_TARGET" = "$PHP_VER_CURRENT" ]; then
         # current and target php version are the same
-        echo "🤞 Skipping install for $PHP_VER_TARGET as current version is the same $PHP_VER_CURRENT" | tee -a $DBGLOG
+        logit "🤞 Skipping install for $PHP_VER_TARGET as current version is the same $PHP_VER_CURRENT" | tee -a $DBGLOG
 
     elif [ -n "$PHP_VER_TARGET" ]; then
         # current and target php version are different - continue with install
         php_install_via_valet $target_php_version
 
     else
-        echo "🧐 Skipping install, unknown request" | tee -a $DBGLOG
+        logit "🧐 Skipping install, unknown request" | tee -a $DBGLOG
     fi
 
     #
@@ -470,9 +486,9 @@ function php_install() {
     #
     export_php_env_and_path $target_php_version
     composer_global_install $target_php_version
-    echo "returning....." && return
+    logit "returning....." && return
 
-    echo "✨ Composer Global root packages "
+    logit "✨ Composer Global root packages "
     composer global --no-interaction show -D 2>>$DBGLOG | awk '{print $1":"$2}'
 
 }
@@ -481,7 +497,7 @@ function php_uninstall() {
     #
     # php_uninstall
     #
-    echo "${FUNCNAME[0]}"
+    logit "${FUNCNAME[0]}"
     sudo -v
     #
     # all php versions will be uninstalled when running valet uninstall --force
@@ -489,14 +505,14 @@ function php_uninstall() {
     #
     valet_uninstall
 
-    echo "🤞 Uninstall brew Formula + Php"
+    logit "🤞 Uninstall brew Formula + Php"
 
     phps="shivammathur/php/php $(for ver in $PHP_VERSIONS; do echo shivammathur/php/php@$ver; done)"
     formulas="$(for ext in $PHP_EXTENSIONS; do for ver in $PHP_VERSIONS; do echo $ext@$ver; done; done | xargs)"
 
     HOMEBREW_NO_INSTALL_CLEANUP=true brew uninstall --force composer php $phps $formulas composer
 
-    echo "🤞 Uninstall brew services"
+    logit "🤞 Uninstall brew services"
     for formula in $(brew services list | grep '^php' | cut -d' ' -f1); do
         sudo brew services stop $formula >>$DBGLOG 2>&1
         #sudo brew services remove $formula >>$DBGLOG 2>&1
@@ -504,7 +520,7 @@ function php_uninstall() {
         #brew services remove $formula >>$DBGLOG 2>&1
     done
 
-    echo "🤞 Tidy brew folders"
+    logit "🤞 Tidy brew folders"
     find /usr/local/Cellar -type d -empty -maxdepth 1 -exec rm -rf {} \; || true
     sudo /bin/rm -rf /usr/local/Cellar/php@* /usr/local/Cellar/php || true
     sudo /bin/rm -f $(brew --prefix)/bin/valet >>$DBGLOG 2>&1 || true
@@ -527,7 +543,7 @@ function switch_php() {
     switch_prompt="${2:-skip}" # prompt makes interactive
 
     if ! is_php_installed "$1" &>/dev/null; then
-        echo "✨ php switch: php $1 needs to be installed"
+        logit "✨ php switch: php $1 needs to be installed"
         php_install "$1"
         return $?
     fi
